name: Go Style Check

on:
  pull_request:
    branches:
      - master

jobs:
  style-check:
    uses: ./go-setup.yml

    steps:
      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          # Add any additional linters or options you want to use
          args: --enable-all

      - name: Run golangci-lint
        run: golangci-lint run ./...