name: Golang checks

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: Install dependencies
        run: |
          go get 
          go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./...
      - name: Go lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54