name: Go Style and test

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Check out code
        uses: actions/checkout@v2

  style-check:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          # Add any additional linters or options you want to use
          args: --enable-all

      - name: Run golangci-lint
        run: golangci-lint run ./...

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Get dependencies
        run: go install -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...