name: Golang checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          # Add any additional linters or options you want to use
          args: --enable-all
      - name: Run golangci-lint
        run: golangci-lint run ./...
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test