name: Go Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    uses: ./go-setup.yml

    steps:
      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v ./...